package-lock.json
package.json
src/app/(collapsable)/forms/[formId]/page.tsx
src/app/(formViewer)/view/[formId]/page.tsx
src/components/formEditor.tsx
src/components/formEditorPage.tsx
src/components/formViewer/formFields.tsx
src/components/formViewer/formViewer.tsx
src/components/formViewer/welcomeScreen.tsx
src/components/ui/tooltip.tsx

As user, In form editor i can see preview of form on same page #29

---

package-lock.json
package.json
src/app/(formEditorPage)/forms/[formId]/conversations/layout.tsx
src/app/(formEditorPage)/forms/[formId]/layout.tsx
src/components/appNavbar/appNavBar.tsx
src/components/conversationDetail.tsx
src/components/conversationList.tsx
src/components/copyLinkButton.tsx
src/components/formEditor/conversationsCard.tsx
src/components/formEditor/formEditPage.tsx
src/components/formEditor/formNameInput.tsx
src/components/formEditor/formPreview.tsx
src/components/formEditor/navLinks.tsx
src/components/formViewer/formViewer.tsx
src/components/transcriptCard.tsx
src/components/ui/browserWindow.tsx
src/components/ui/sidebar-nav.tsx
src/components/ui/tabs.tsx
src/lib/dbControllers/form.ts

Changes in form page

---

prisma/schema.prisma

Reverts growupanand/smart-form-wizard#79

Revert "Added DIRECT_URL in db schema to make prisma work with pool connection"

---

src/components/appNavbar/appNavBar.tsx
src/components/formEditor/formEditPage.tsx
src/components/formEditor/formEditorForm.tsx
src/components/formListItem.tsx
src/components/formViewer/endScreen.tsx
src/components/formViewer/formFields.tsx
src/components/homepage/header.tsx
src/components/workspaceHeader.tsx

- Improve form editor placeholders text
- Used icons in buttons
- Added brand name and link at end screen of form subbmission
- Added submit button in form submission page

112 UI improvements

---

package-lock.json
package.json
src/app/api/form/[formId]/getNextFormField/route.ts
src/components/formEditor/formEditorForm.tsx
src/lib/services/conversation.ts
src/lib/services/generateFormField.ts
src/lib/services/openAI.ts
src/lib/services/systemPrompt.ts
src/lib/validations/form.ts

As user, In form editor page I can auto generate form field #59

---

src/app/(dashboard)/dashboard/loading.tsx
src/app/(dashboard)/dashboard/page.tsx
src/app/(dashboard)/layout.tsx
src/app/(formEditorPage)/forms/[formId]/conversations/layout.tsx
src/app/(publicPage)/layout.tsx
src/app/fonts.ts
src/components/appNavbar/appNavBar.tsx
src/components/dashboard/dataCard.tsx
src/components/formEditor/conversationDetail.tsx
src/components/formEditor/conversationsListCard.tsx
src/components/formEditor/conversationsSidebar.tsx
src/components/formEditor/formEditPage.tsx
src/components/formEditor/formEditorForm.tsx
src/components/formEditor/formEditorPageHeader.tsx
src/components/formEditor/formNameInput.tsx
src/components/formEditor/navLinks.tsx
src/components/formList.tsx
src/components/homepage/features.tsx
src/components/homepage/header.tsx
src/components/homepage/hero.tsx
src/components/homepage/howToUse.tsx
src/components/homepage/pricing.tsx
src/components/homepage/sectionCard.tsx
src/components/ui/sidebar-nav.tsx

137 add dashboard page

---

src/components/wrappers/OrganizationRequired.tsx
src/lib/getOrganizationId.ts

Page was crashed if no organization is created
✅ Closes: #166

fix: 🐛 Unauthorized getOrganizationId(src/lib/getOrganizationId

---

apps/web/src/app/api/trpc/[trpc]/route.ts
packages/db/package.json
packages/db/src/db.ts
pnpm-lock.yaml

182 convert tRPC routes into edge runtime routes

---

apps/web/src/app/api/trpc/[trpc]/route.ts
packages/db/package.json
packages/db/src/db.ts
pnpm-lock.yaml

Reverts growupanand/ConvoForm#183
There is no performance improvement, Instead it insrease the response time.

Revert "182 convert tRPC routes into edge runtime routes"

---

apps/web/src/app/(protectedPage)/forms/[formId]/_components/formPageHeader.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/not-found.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/page.tsx

Anyone can edit any form using the form link even it is not in there organization
✅ Closes: #194

fix: 🐛 Anyone can edit any form using the form link even it is

---

apps/web/src/app/(protectedPage)/(mainPage)/workspaces/[workspaceId]/_component/createFormButton.tsx
apps/web/src/app/(protectedPage)/(mainPage)/workspaces/[workspaceId]/_component/pageHeader.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/changeNameInput.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx
apps/web/src/app/api/ai/generateForm/route.ts
apps/web/src/app/api/form/[formId]/conversation/route.ts
apps/web/src/app/api/form/[formId]/getNextFormField/route.ts
apps/web/src/components/formSubmissionPage/formViewer.tsx
apps/web/src/components/mainPage/navigationCardContent.tsx
apps/web/src/lib/errorHandlers.ts
apps/web/src/trpc/react.tsx
packages/api/index.ts
packages/api/src/lib/rateLimit.ts
packages/api/src/router/form.ts
packages/api/src/router/workspace.ts
packages/ui/src/components/ui/use-toast.ts

refactor: 💡 fixed ratelimit error message toast

---

apps/web/src/app/(landingPage)/_components/userButton.tsx
apps/web/src/app/(landingPage)/layout.tsx
apps/web/src/app/(protectedPage)/layout.tsx
apps/web/src/app/auth/layout.tsx
apps/web/src/app/layout.tsx

Moved clerk provider to root layout, and make root page force static rendered
✅ Closes: #206

fix: 🐛 Sometimes form editor page not loading

---

apps/web/src/app/(protectedPage)/(mainPage)/workspaces/[workspaceId]/_component/createFormButton.tsx
apps/web/src/app/(protectedPage)/(mainPage)/workspaces/[workspaceId]/_component/formListItem.tsx
apps/web/src/app/(protectedPage)/(mainPage)/workspaces/[workspaceId]/_component/generateForm.tsx
apps/web/src/app/(protectedPage)/(mainPage)/workspaces/[workspaceId]/_component/pageHeader.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/changeNameInput.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx
apps/web/src/components/mainPage/navigationCardContent.tsx

fix: 🐛 tanstack mutate query raise false uncaught error

---

apps/web/src/app/(protectedPage)/(mainPage)/dashboard/_components/recentResponseList.tsx
apps/web/src/app/(protectedPage)/(mainPage)/workspaces/[workspaceId]/_component/formList.tsx
apps/web/src/app/(protectedPage)/(mainPage)/workspaces/[workspaceId]/_component/formListItem.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/conversations/_components/conversationsNavigation.tsx
apps/web/src/components/common/listItem.tsx
apps/web/src/components/common/secondaryNavigation.tsx
apps/web/src/components/mainPage/navigationCardContent.tsx

210 load list items with stagger animation

---

apps/web/next.config.mjs
apps/web/src/app/(formSubmissionPage)/view/[formId]/page.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formCustomize.tsx
packages/api/src/router/form.ts
packages/db/drizzle/migrations/0005_secret_king_cobra.sql
packages/db/drizzle/migrations/meta/0005_snapshot.json
packages/db/drizzle/migrations/meta/_journal.json
packages/db/src/schema/form.ts

If you enable show company logo in form, Current organization logo where form was created, will be shown on the form submission page header
✅ Closes: 218
**Screenshots**
<table>
<tr>
<td><img width="923" alt="image" src="https://github.com/growupanand/ConvoForm/assets/29487686/a6ecf2e9-ccee-4e3f-82e2-a9e5edfe0c07"></td>
<td><img width="608" alt="image" src="https://github.com/growupanand/ConvoForm/assets/29487686/3d67b1e4-e7e2-4fe2-b817-6158175145b5"></td>
</tr>
</table>

feat: 🚀 As form creator, I can add my company logo to the form

---

README.md

Thanks for making this project public ❤️
Listed extra services which are used as prerequisites.  Having these are crucial to run the project.

Adding 3rd party prerequisites to README.md

---

apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx
apps/web/src/lib/validations/form.ts

when user is editing the form, he want to experiment with different fields, so we can allow him to restore a deleted field. Now user can undo the deleted field. I had added the undo button If user click on delete then undo button will appear. 
[Issue Link](https://github.com/growupanand/ConvoForm/issues/56) resolve #56

In form editor, After remove a form field I can undo this remove Fixed

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/documentation_update.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/infrastructure_work.yml
.github/workflows/GSSoC_workflow.yml
.github/workflows/comment_on_merge.yml

- It also fixes some issue in GSSoC_workflow.yml file where it also labelling the contributor 'gssoc' who is not the Part of GSSoC.
- This PR solves issue #287

Fix related to workflow

---

.vscode/settings.json
apps/web/src/app/(protectedPage)/(mainPage)/workspaces/[workspaceId]/_component/createFormButton.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/conversations/_components/conversationDetail.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/conversations/_components/transcriptCard.tsx
apps/web/src/app/api/ai/generateForm/route.ts
apps/web/src/app/api/form/[formId]/conversation/route.ts
apps/web/src/lib/services/conversation.ts
apps/web/src/lib/services/systemPrompt.ts
apps/web/src/lib/types/transcript.ts
packages/api/src/router/form.ts
packages/db/drizzle/migrations/0012_abnormal_skullbuster.sql
packages/db/drizzle/migrations/0013_optimal_toad.sql
packages/db/drizzle/migrations/meta/0012_snapshot.json
packages/db/drizzle/migrations/meta/0013_snapshot.json
packages/db/drizzle/migrations/meta/_journal.json
packages/db/src/schema/base.ts
packages/db/src/schema/conversations/conversation.ts
packages/db/src/schema/conversations/validation.ts
packages/db/src/schema/formFields/formField.ts
packages/db/src/schema/formFields/validation.ts
packages/db/src/schema/forms/form.ts
packages/db/src/schema/organizationMembers/organizationMember.ts
packages/db/src/schema/organizations/organization.ts
packages/db/src/schema/users/user.ts
packages/db/src/schema/workspaces/workspace.ts
packages/db/src/script.ts
packages/react/src/hooks/useConvoForm.ts
packages/react/src/types.ts
packages/react/src/utils/streamUtils.ts

Added new columns `formDescription` and `inputType` in the `formField` table and other changes.

293 in db schema add input type field for the table formfield

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/documentation_update.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/infrastructure_work.yml
.github/workflows/GSSoC_workflow.yml
.github/workflows/comment_on_merge.yml

- It also fixes some issue in GSSoC_workflow.yml file where it also labelling the contributor 'gssoc' who is not the Part of GSSoC.
- and minor fixes in Issue templates.
- This PR solves issue #287

[Bug]: Fix related to workflows

---

apps/web/src/app/(protectedPage)/(mainPage)/workspaces/[workspaceId]/_component/createFormButton.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/fieldsEditorCard/addFieldItem.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/fieldsEditorCard/editFieldSheet.tsx
packages/api/src/router/form.ts
packages/db/drizzle/migrations/0014_nifty_stephen_strange.sql
packages/db/drizzle/migrations/meta/0014_snapshot.json
packages/db/drizzle/migrations/meta/_journal.json
packages/db/src/schema/conversations/validation.ts
packages/db/src/schema/formFields/constants.ts
packages/db/src/schema/formFields/formField.ts
packages/db/src/schema/formFields/validation.ts

chore: 🤖 Added Input type selector in Edit Field Sheet

---

.vscode/settings.json
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/fieldsEditorCard/editFieldSheet.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/fieldsEditorCard/inputConfigurationEditor/index.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/fieldsEditorCard/inputConfigurationEditor/multiChoiceInputConfiguration.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/fieldsEditorCard/inputConfigurationEditor/textInputConfigurationEditor.tsx
apps/web/src/app/api/form/[formId]/conversation/_utils.ts
apps/web/src/app/api/form/[formId]/conversation/route.ts
apps/web/src/components/formViewer/FormFieldsViewer.tsx
apps/web/src/components/formViewer/formViewer.tsx
packages/db/src/schema/conversations/validation.ts
packages/db/src/schema/formFields/validation.ts
packages/db/src/schema/forms/form.ts

Form creator can now customize input configuration according to the input type. E.g. In text input type they can customize the input placeholder text
✅ Closes: 305
**Screenshots**

feat: 🚀 Added Input Configuration editor in Edit Field Sheet

---

apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/fieldsEditorCard/editFieldSheet.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/fieldsEditorCard/inputConfigurationEditor/index.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/fieldsEditorCard/inputConfigurationEditor/multiChoiceInputConfiguration.tsx
packages/db/src/schema/formFields/validation.ts
packages/ui/src/components/ui/form.tsx

Form creator now select "Multiple choice" Input type and can add choices
✅ Closes: 301
**Screenshots**

feat: 🚀 Added Multi choices Input type editor

---

apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/fieldsEditorCard/inputConfigurationEditor/multiChoiceInputConfiguration.tsx
apps/web/src/components/formViewer/DynamicAnswerInput/index.tsx
apps/web/src/components/formViewer/DynamicAnswerInput/multiChoiceInput.tsx
apps/web/src/components/formViewer/DynamicAnswerInput/textInput.tsx
apps/web/src/components/formViewer/FormFieldsViewer.tsx
apps/web/src/components/formViewer/formViewer.tsx
packages/db/src/schema/formFields/constants.ts
packages/db/src/schema/formFields/validation.ts
packages/react/src/hooks/useConvoForm.ts
packages/react/src/index.ts
packages/react/src/types.ts

Respondent can now choose answer from given choices
✅ Closes: 308
**Screenshots**

feat: 🚀 Added Multi Choice Answer Input in Form submission page

---

packages/react/src/utils/url.ts

fix: 🐛 Added vercel deployment support for useConvoForm

---

packages/react/src/utils/url.ts

fix: 🐛 Added URL support from NEXT_PUBLIC_APP_URL in useconvofo

---

.vscode/settings.json
apps/web/src/app/(protectedPage)/(mainPage)/workspaces/[workspaceId]/_component/createFormButton.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/changeNameInput.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/fieldsEditorCard/addFieldItem.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/fieldsEditorCard/editFieldItem.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/fieldsEditorCard/editFieldSheet.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/page.tsx
packages/api/src/router/formField.ts

refactor: 💡 Added delete form field button

---

apps/web/src/components/formViewer/formViewer.tsx
apps/web/src/components/formViewer/topProgressBar.tsx
packages/ui/package.json
packages/ui/src/components/ui/progress.tsx
pnpm-lock.yaml

As a Respondent, I can see current form submission progress bar in top edge screen
✅ Closes: 249
**Screenshot**

feat: 🚀 Added submission progress bar

---

apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx
apps/web/src/app/api/form/[formId]/conversation/_utils.ts
apps/web/src/app/api/form/[formId]/conversation/route.ts
apps/web/src/lib/services/conversation.ts
packages/db/src/schema/formFields/constants.ts

✅ Closes: 331
When user will click on choice button to answer the question, this answer will not be validate by AI, instead will be saved exact value in database

perf: ⚡️ Multi choice answer will save exact value WO validation

---

.vscode/launch.json
apps/web/src/app/(formSubmissionPage)/view/[formId]/page.tsx
apps/web/src/app/(protectedPage)/(mainPage)/workspaces/[workspaceId]/_component/generateFormModal.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formPreview.tsx
apps/web/src/app/api/form/[formId]/conversation/route.ts
apps/web/src/components/formViewer/DynamicAnswerInput/datePicker.tsx
apps/web/src/components/formViewer/DynamicAnswerInput/index.tsx
apps/web/src/components/formViewer/askScreen.tsx
apps/web/src/components/formViewer/index.tsx
apps/web/src/components/formViewer/topProgressBar.tsx
apps/web/src/lib/services/conversation.ts
apps/web/src/lib/services/systemPrompt.ts
packages/api/src/router/conversation.ts
packages/api/src/router/form.ts
packages/api/src/trpc.ts
packages/db/src/schema/formFields/index.ts
packages/db/src/schema/formFields/utils.ts
packages/ui/src/components/ui/calendar.tsx

As form respondent, I can answer the question by picking date from Date picker
✅ Closes: 336
✅ Closes: #336

feat: 🚀 Added DatePicker answer input

---

packages/api/src/router/conversation.ts

✅ Closes: 340
✅ Closes: #(issue)

fix: 🐛 Unbale to see conversation responses list

---

.gitignore
apps/web/next.config.mjs
apps/web/package.json
apps/web/sentry.client.config.ts
apps/web/src/instrumentation.ts
pnpm-lock.yaml

Integrated Sentry's user feedback feature, this allow user to report any bug or suggestion by clicking on floating button "Report a bug" while using the app.
✅ Closes: #345

345 infrastructure add report bug button

---

packages/api/src/router/conversation.ts

✅ Closes: 349
✅ Closes: #(issue)

fix: 🐛 Internal error after open old conversation page

---

apps/web/src/app/(protectedPage)/(mainPage)/workspaces/[workspaceId]/_component/formList.tsx

fix: 🐛 In workspace page new form not showing without reload

---

apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/customizeEndScreenCard.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/customizeFormCard.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formEditorCard.tsx
apps/web/src/components/formViewer/endScreen.tsx
apps/web/src/components/formViewer/index.tsx
packages/api/src/router/form.ts
packages/db/drizzle/migrations/0016_old_gateway.sql
packages/db/drizzle/migrations/0017_blue_cerebro.sql
packages/db/drizzle/migrations/meta/0016_snapshot.json
packages/db/drizzle/migrations/meta/0017_snapshot.json
packages/db/drizzle/migrations/meta/_journal.json
packages/db/src/schema/forms/form.ts
packages/db/src/schema/forms/validation.ts

- Implemented functionality to display a custom link on the final screen after form submission.
- Added button to allow users to navigate to the specified link after submitting the form.
✅ Closes: #348

feat: 🚀add custom link option on final form submission screen

---

apps/web/src/components/common/typingEffect.tsx
apps/web/src/components/formViewer/askScreen.tsx

✅ Closes: 149
Added typing effect while showing the question in form submission page.
✅ Closes: #149

style: 💄 improve typing effect while showing question

---

CHANGELOG.md
apps/web/src/app/(protectedPage)/(mainPage)/workspaces/[workspaceId]/_component/createFormButton.tsx
apps/web/src/app/(protectedPage)/(mainPage)/workspaces/[workspaceId]/_component/generateFormModal.tsx
package.json
packages/release/src/changeLogs.ts
packages/release/src/releases/index.ts
packages/release/src/scripts/updateReleaseList.ts

✅ Closes: 298
In the modal for "Generate form by AI", you can now pre-fill text by choosing a template from the dropdown.
✅ Closes: #298

feat: 🚀 fill text from templates for generate form by AI

---

.github/workflows/prepare-release.yml
apps/web/src/app/(landingPage)/_components/constants.ts
apps/web/src/app/(landingPage)/_components/demoCard.tsx
apps/web/src/app/(landingPage)/_components/hero.tsx
apps/web/src/app/(landingPage)/_components/sectionShell.tsx
apps/web/src/app/(landingPage)/page.tsx
apps/web/src/app/(protectedPage)/_components/desktopOnlyAlert.tsx
apps/web/src/app/(protectedPage)/auth/layout.tsx
apps/web/src/app/(protectedPage)/auth/register/[[...sign-up]]/page.tsx
apps/web/src/app/(protectedPage)/auth/sign-in/[[...sign-in]]/page.tsx
apps/web/src/app/(protectedPage)/organizations/page.tsx
apps/web/src/components/authProvider.tsx
apps/web/src/components/common/browserWindow.tsx
apps/web/src/components/common/responsiveModal.tsx
apps/web/src/components/common/topHeader.tsx
apps/web/src/components/formViewer/formDesignContext.tsx

Added demo section in landing page for desktop screen only, In this section a live demo form will show which user can fill to experience the convo form.
✅ Closes: #363

363 create demo section in landing page

---

apps/web/package.json
apps/web/src/app/(protectedPage)/forms/[formId]/conversations/[conversationId]/layout.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/conversations/_components/conversationsNavigation.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/conversations/_components/conversationsSidebar.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/conversations/_components/conversationsStatsCard.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/conversations/_components/data-table/conversations-data-table.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/conversations/table/page.tsx
apps/web/src/components/common/secondaryNavigation.tsx
apps/web/src/components/common/statsCard.tsx
packages/api/src/router/conversation.ts
packages/ui/package.json
pnpm-lock.yaml

as form creator, i can see form responses related stats, E.g Total count, completed count, partial count, live count
✅ Closes: #375

feat: 🚀 add stats page for form responses

---

CHANGELOG.md
apps/web/package.json
apps/web/src/app/(formSubmissionPage)/view/[formId]/page.tsx
apps/web/src/components/common/browserWindow.tsx
apps/web/src/components/common/typingEffect.tsx
apps/web/src/components/formViewer/askScreen.tsx
apps/web/src/components/formViewer/index.tsx
apps/web/src/components/formViewer/topProgressBar.tsx
apps/web/src/components/formViewer/welcomeScreen.tsx
package.json
packages/release/src/changeLogs.ts
packages/release/src/releases/index.ts
packages/release/src/releases/release_0_16_0.mdx
packages/ui/package.json
packages/ui/src/components/ui/progress.tsx
pnpm-lock.yaml

respondant can reset form and start from beginning
✅ Closes: #403
Add an button "Start over" in form submission page, By clicking this button respondant can reset there form submission progress and start from the beginning.
https://github.com/user-attachments/assets/4e144359-bd99-4908-8ea8-d8b8732be34d

feat: 🚀 add start over button in form submit page release: 0.16.0

---

apps/web/src/app/(formSubmissionPage)/view/[formId]/_components/formDesignLayout.tsx
apps/web/src/app/(formSubmissionPage)/view/[formId]/page.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/formPreviewBrowser.tsx
apps/web/src/components/formViewer/askScreen.tsx
apps/web/src/components/formViewer/endScreen.tsx
apps/web/src/components/formViewer/index.tsx
apps/web/src/components/formViewer/topProgressBar.tsx
apps/web/src/components/formViewer/welcomeScreen.tsx

style: 💄 formviewer is not more responsive for different screen

---

apps/web/src/app/(protectedPage)/(mainPage)/workspaces/[workspaceId]/_component/formListItem.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/conversations/_components/conversationsSidebar.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/conversations/_components/data-table/conversations-data-table.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/conversations/page.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/conversations/table/page.tsx
apps/web/src/app/layout.tsx
apps/web/src/components/conversationsStats.tsx
apps/web/src/components/statsComponents/answersStatsComponents/multiChoiceStats.tsx
apps/web/src/components/statsComponents/statsGrid.tsx
packages/api/src/router/conversation.ts
packages/ui/src/components/ui/progress.tsx
packages/ui/src/components/ui/table.tsx

feat: 🚀 enhanced ConversationsStatsPage with MultiChoiceStats

---

CHANGELOG.md
package.json
packages/release/src/changeLogs.ts
packages/release/src/releases/index.ts
packages/release/src/releases/release_0_18_0.mdx

prepare release

---

apps/web/src/app/(protectedPage)/forms/[formId]/_components/formEditor/fieldsEditorCard/inputConfigurationEditor/multiChoiceInputConfiguration.tsx
apps/web/src/components/formViewer/DynamicAnswerInput/multiChoiceInput.tsx
apps/web/src/components/formViewer/topProgressBar.tsx
packages/db/src/schema/formFields/validation.ts
packages/tailwind-config/src/tailwind.config.ts
packages/ui/src/components/ui/button.tsx
packages/ui/src/components/ui/input.tsx
packages/ui/src/components/ui/progress.tsx

434 text overflow in mcq

---

apps/web/package.json
apps/web/src/app/(protectedPage)/forms/[formId]/conversations/_components/collectedDataTable.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/conversations/_components/conversationDetail.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/conversations/_components/metadataCard.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/conversations/_components/transcriptCard.tsx
apps/web/src/app/api/playground/route.ts
apps/web/src/components/statsComponents/statsTitle.tsx
apps/web/src/middleware.ts
packages/api/package.json
packages/api/src/router/conversation.ts
packages/db/drizzle/migrations/0022_hard_marvel_zombies.sql
packages/db/drizzle/migrations/meta/0022_snapshot.json
packages/db/drizzle/migrations/meta/_journal.json
packages/db/src/schema/conversations/conversation.ts
packages/db/src/schema/conversations/validation.ts
packages/ui/src/components/sectionHeading.tsx
packages/ui/src/index.tsx
pnpm-lock.yaml

439 add form respondent metadata collection and display

---

apps/web/src/app/(protectedPage)/forms/[formId]/conversations/_components/conversationDetail.tsx
apps/web/src/app/(protectedPage)/forms/[formId]/conversations/_components/data-table/conversations-data-table.tsx
apps/web/src/app/(public)/(landingPage)/_components/demoSection/liveDemoResponses.tsx
apps/web/src/components/StatusBadge.tsx

showing `object` instead of actual value
✅ Closes: #447
✅ Closes: #<issue_number>

fix: 🐛 invalid value showing in CSV file
